#ifndef NAUTILUS_CAMERA_COORDINATE_SYSTEM_AXIS
#define NAUTILUS_CAMERA_COORDINATE_SYSTEM_AXIS

namespace nautilus {

    enum NautilusCameraCoordinateSystemAxis {
        NAUTILUS_CAMERA_COORDINATE_SYSTEM_AXIS_FWD,
        NAUTILUS_CAMERA_COORDINATE_SYSTEM_AXIS_RGT,
        NAUTILUS_CAMERA_COORDINATE_SYSTEM_AXIS_UP,
    };

}

#endif      // NAUTILUS_CAMERA_COORDINATE_SYSTEM_AXIS