#ifndef NAUTILUS_CAMERA_COORDINATE_SYSTEM_AXIS
#define NAUTILUS_CAMERA_COORDINATE_SYSTEM_AXIS

namespace nautilus {

    enum NautilusCameraCoordinateSystemAxis {
        NAUTILUS_CAMERA_COORDINATE_SYSTEM_AXIS_X,
        NAUTILUS_CAMERA_COORDINATE_SYSTEM_AXIS_Y,
        NAUTILUS_CAMERA_COORDINATE_SYSTEM_AXIS_Z
    };

}

#endif      // NAUTILUS_CAMERA_COORDINATE_SYSTEM_AXIS