#ifndef NAUTILUS_CAMERA_MOVEMENT_DIRECTION_HPP
#define NAUTILUS_CAMERA_MOVEMENT_DIRCETION_HPP

namespace nautilus {

    enum NautilusCameraMovementDirection {
        NAUTILUS_CAMERA_MOVEMENT_DIRECTION_FORWARD,
        NAUTILUS_CAMERA_MOVEMENT_DIRECTION_BACKWARD,
        NAUTILUS_CAMERA_MOVEMENT_DIRECTION_LEFT,
        NAUTILUS_CAMERA_MOVEMENT_DIRECTION_RIGHT,
        NAUTILUS_CAMERA_MOVEMENT_DIRECTION_UP,
        NAUTILUS_CAMERA_MOVEMENT_DIRECTION_DOWN
    };

}

#endif      // NAUTILUS_CAMERA_MOVEMENT_DIRECTION_HPP