#ifndef NAUTILUS_CAMERA_MODE_HPP
#define NAUTILUS_CAMERA_MODE_HPP

enum NautilusCameraMode {
    NAUTILUS_CAMERA_MODE_FPS,
    NAUTILUS_CAMERA_MODE_FOCUS,
    NAUTILUS_CAMERA_MODE_2D
};

#endif      // NAUTILUS_CAMERA_MODE_HPP