#ifndef NAUTILUS_SHADER_COMPONENT_UNIFORM_IN_OUT_HPP
#define NAUTILUS_SHADER_COMPONENT_UNIFORM_IN_OUT_HPP

namespace nautilus {

    enum NautilusShaderComponentUniformInOut {
        NAUTILUS_SHADER_COMPONENT_UNIFORM_IN,
        NAUTILUS_SHADER_COMPONENT_UNIFORM_OUT
    };

}

#endif      // NAUTILUS_SHADER_COMPONENT_UNIFORM_IN_OUT_HPP