#ifndef NAUTILUS_SHADER_STAGE_HPP
#define NAUTILUS_SHADER_STAGE_HPP

namespace nautilus {

    enum NautilusShaderStage {
        NAUTILUS_SHADER_STAGE_VERTEX,
        NAUTILUS_SHADER_STAGE_FRAGMENT,
        NAUTILUS_SHADER_STAGE_GEOMETRY,
        NAUTILUS_SHADER_STAGE_COMPUTE,
        NAUTILUS_SHADER_STAGE_TESSELATION,
        NAUTILUS_SHADER_STAGE_TESSELATION_EVALUATION,
        NAUTILUS_SHADER_STAGE_TESSELATION_CONTROL
    };

}

#endif      // NAUTILUS_SHADER_STAGE_HPP