#ifndef NAUTILUS_INTERFACE_HPP
#define NAUTILUS_INTERFACE_HPP

enum NautilusInterface {
    NAUTILUS_INTERFACE_OPENGL,
    NAUTILUS_INTERFACE_VULKAN,
    NAUTILUS_INTERFACE_DEFAULT = NAUTILUS_INTERFACE_OPENGL
};

#endif      // NAUTILUS_INTERFACE_HPP