#ifndef NAUTILUS_API_HPP
#define NAUTILUS_API_HPP

enum NautilusAPI {
    NAUTILUS_API_UNSPECIFIED = 0,
    NAUTILUS_API_OPENGL      = 1,
    NAUTILUS_API_VULKAN      = 2
};

#endif         // NAUTILUS_API_HPP