#ifndef NAUTILUS_SHADER_TESSELATION_CONTROL_CPP
#define NAUTILUS_SHADER_TESSELATION_CONTROL_CPP

#include "NautilusShaderTesselationControl.hpp"



#endif      // NAUTILUS_SHADER_TESSELATION_CONTROL_CPP